spring.datasource.url=jdbc:postgresql://localhost:5432/eduaircontrol
spring.datasource.username=eduair_user
spring.datasource.password=eduair_pass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect