spring.application.name=backend
spring.datasource.url=jdbc:postgresql://postgres:5432/eduaircontrol
spring.datasource.username=eduair_user
spring.datasource.password=eduair_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mi_clave_super_segura_de_mas_de_32_caracteres
jwt.expiration=86400000 