CREATE TABLE seguridad.usuario (
    id_usuario       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL,
    apellido         VARCHAR(100) NOT NULL,
    email            VARCHAR(254) NOT NULL UNIQUE,
    username         VARCHAR(50) NOT NULL UNIQUE,
    estado_cuenta    VARCHAR(20) NOT NULL DEFAULT 'ACTIVA',
    fecha_registro   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimo_acceso    TIMESTAMPTZ,
    foto_perfil      VARCHAR(500),
    CONSTRAINT ck_usuario_estado_cuenta
        CHECK (estado_cuenta IN ('ACTIVA', 'INACTIVA', 'BLOQUEADA', 'PENDIENTE'))
);
