CREATE TABLE seguridad.credencial (
    id_credencial         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id            INTEGER NOT NULL,
    password_hash         VARCHAR(255),
    proveedor_auth        VARCHAR(30) NOT NULL DEFAULT 'LOCAL',
    fecha_creacion        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_credencial_proveedor_auth
        CHECK (proveedor_auth IN ('LOCAL', 'GOOGLE', 'FACEBOOK')),
    CONSTRAINT ck_credencial_password_local
        CHECK (proveedor_auth <> 'LOCAL' OR password_hash IS NOT NULL),
    CONSTRAINT uq_credencial_usuario_proveedor UNIQUE (usuario_id, proveedor_auth)
);
