CREATE TABLE seguridad.rol (
    id_rol        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol    VARCHAR(50) NOT NULL UNIQUE,
    descripcion   VARCHAR(255),
    estado        VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT ck_rol_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);
