CREATE TABLE seguridad.permiso (
    id_permiso        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso    VARCHAR(100) NOT NULL UNIQUE,
    descripcion       VARCHAR(255),
    modulo            VARCHAR(50) NOT NULL
);
