CREATE TABLE seguridad.usuario_rol (
    id_usuario_rol     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         INTEGER NOT NULL,
    rol_id             INTEGER NOT NULL,
    fecha_asignacion   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usuario_rol UNIQUE (usuario_id, rol_id)
);
