CREATE TABLE seguridad.rol_permiso (
    id_rol_permiso   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id           INTEGER NOT NULL,
    permiso_id       INTEGER NOT NULL,
    CONSTRAINT uq_rol_permiso UNIQUE (rol_id, permiso_id)
);
