CREATE TABLE seguridad.token_sesion (
    id_token           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         INTEGER NOT NULL,
    token              VARCHAR(512) NOT NULL UNIQUE,
    ip_acceso          VARCHAR(45),
    dispositivo        VARCHAR(255),
    fecha_creacion     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion   TIMESTAMPTZ NOT NULL,
    estado             VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT ck_token_sesion_estado CHECK (estado IN ('ACTIVO', 'REVOCADO', 'EXPIRADO')),
    CONSTRAINT ck_token_sesion_fechas CHECK (fecha_expiracion > fecha_creacion)
);
