CREATE TABLE seguridad.verificacion_2fa (
    id_verificacion      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id           INTEGER NOT NULL,
    codigo               VARCHAR(255) NOT NULL,
    fecha_generacion     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion     TIMESTAMPTZ NOT NULL,
    estado               VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT ck_verificacion_2fa_estado
        CHECK (estado IN ('PENDIENTE', 'VERIFICADO', 'EXPIRADO', 'CANCELADO')),
    CONSTRAINT ck_verificacion_2fa_fechas CHECK (fecha_expiracion > fecha_generacion)
);
