CREATE TABLE seguridad.recuperacion_password (
    id_recuperacion       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id            INTEGER NOT NULL,
    token_recuperacion    VARCHAR(255) NOT NULL UNIQUE,
    fecha_solicitud       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion      TIMESTAMPTZ NOT NULL,
    estado                VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT ck_recuperacion_password_estado
        CHECK (estado IN ('PENDIENTE', 'USADO', 'EXPIRADO', 'CANCELADO')),
    CONSTRAINT ck_recuperacion_password_fechas CHECK (fecha_expiracion > fecha_solicitud)
);
