CREATE TABLE seguridad.auditoria_evento (
    id_evento       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      INTEGER,
    accion          VARCHAR(100) NOT NULL,
    modulo          VARCHAR(50) NOT NULL,
    descripcion     VARCHAR(1000),
    ip              VARCHAR(45),
    fecha_evento    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
