version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eduaircontrol-db
    restart: always
    environment:
      POSTGRES_DB: eduaircontrol
      POSTGRES_USER: eduair_user
      POSTGRES_PASSWORD: eduair_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: