pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                // Si usas Maven
                sh './mvnw clean install'
                // O si usas Gradle
                // sh './gradlew build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t springboot-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8080:8080 --name springboot-app springboot-app'
            }
        }
    }

    post {
        success {
            echo " Pipeline exitoso: Spring Boot app desplegada en Docker."
        }
        failure {
            echo " Pipeline falló. Revisa los logs."
        }
    }
}
